version: "3.7"

volumes:
    postgres: ~

services:
    postgres:
        image: postgres:11
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - "postgres:/var/lib/postgresql/data"
        ports:
            - "${POSTGRES_PORT}:5432"

    example:
        image: nginx
        ports:
            - "${EXAMPLE_ORG_PORT}:80"
        volumes:
            - "./testdata/example.org:/usr/share/nginx/html:ro"
