version: "3.7"

volumes:
    postgres: ~

services:
    postgres:
        image: postgres:11
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - "postgres:/var/lib/postgresql/data"
        ports:
            - "${POSTGRES_PORT}:5432"

    scraper_target:
        image: nginx
        ports:
            - "${SCRAPER_TARGET_PORT}:80"
        volumes:
            - "./scraper_target:/usr/share/nginx/html:ro"
